server:
  port: 8000
spring:
  application:
    name: manager
logging:
  config: classpath:log4j2.xml
  level:
    cn.jay.repository: info
 # cloud:
 #   nacos:
 #     discovery:
  #      server-addr: localhost:8848