server:
  port: 9000
spring:
  application:
    name: job-quartz
  cache:
    type: caffeine
    caffeine:
      spec: initialCapacity=10,maximumSize=200,expireAfterWrite=3s
 # cloud:
 #   nacos:
 #     discovery:
#        server-addr: localhost:8848
  datasource:
    # 配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    # 配置连接数据库信息
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.16.176:3307/mybatis_plus?characterEncoding=utf-8&useSSL=false
    username: root
    password: zty123456
logging:
  config: classpath:log4j2.xml
  level:
    cn.jay.repository: info

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
     db-config:
       # 配置MyBatis-Plus操作表的默认前缀
       table-prefix: t_
       # 配置MyBatis-Plus的主键策略
       #id-type: auto
  mapper-locations: classpath:/mapper/**.xml

#feign:
#  hystrix:
 #   enabled: true